//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DAL.Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public Sale()
        {
            this.SaleDetails = new HashSet<SaleDetail>();
            this.SalePayments = new HashSet<SalePayment>();
            this.SaleReturnReceives = new HashSet<SaleReturnReceive>();
        }
    
        public long Id { get; set; }
        public System.DateTime SaleDate { get; set; }
        public long SaleInvoiceId { get; set; }
        public System.DateTime SaleInvoiceDate { get; set; }
        public decimal TotalSalePrice { get; set; }
        public decimal DiscountInPercentage { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal VATInPercentage { get; set; }
        public decimal VATAmount { get; set; }
        public decimal ServiceCharge { get; set; }
        public decimal NetAmount { get; set; }
        public string SaleBy { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime SetOn { get; set; }
        public long SetBy { get; set; }
    
        public virtual ICollection<SaleDetail> SaleDetails { get; set; }
        public virtual ICollection<SalePayment> SalePayments { get; set; }
        public virtual ICollection<SaleReturnReceive> SaleReturnReceives { get; set; }
    }
}
