//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DAL.Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleReturnReceive
    {
        public SaleReturnReceive()
        {
            this.SaleReturnReceiveDetails = new HashSet<SaleReturnReceiveDetail>();
        }
    
        public long Id { get; set; }
        public System.DateTime SaleReturnDate { get; set; }
        public long SaleId { get; set; }
        public System.DateTime SaleDate { get; set; }
        public long SaleInvoiceId { get; set; }
        public decimal TotalSalePrice { get; set; }
        public decimal VATInPercentage { get; set; }
        public decimal VATInAmount { get; set; }
        public decimal NetAmount { get; set; }
        public string SaleReturnBy { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime SetOn { get; set; }
        public long SetBy { get; set; }
    
        public virtual Sale Sale { get; set; }
        public virtual ICollection<SaleReturnReceiveDetail> SaleReturnReceiveDetails { get; set; }
    }
}
