//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DAL.Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePayment
    {
        public long Id { get; set; }
        public long SaleId { get; set; }
        public decimal NetAmount { get; set; }
        public decimal ReceivedCashAmount { get; set; }
        public decimal ReceivedCardAmount { get; set; }
        public decimal ReceivedSaleReturnAmount { get; set; }
        public Nullable<long> ReceivedSaleReturnId { get; set; }
        public decimal DiscountInPercentageForCard { get; set; }
        public decimal DiscountAmountForCard { get; set; }
        public Nullable<long> BankIdForCard { get; set; }
        public string CardType { get; set; }
        public string CardNo { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime SetOn { get; set; }
        public long SetBy { get; set; }
    
        public virtual Sale Sale { get; set; }
    }
}
