//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DAL.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStore
    {
        public long Id { get; set; }
        public long PurchaseReceiveDetailId { get; set; }
        public long ProductId { get; set; }
        public int Serial { get; set; }
        public Nullable<long> ProductUnitId { get; set; }
        public Nullable<long> ProductSectionId { get; set; }
        public int ProductQuantity { get; set; }
        public string ProductSizeCode { get; set; }
        public string ProductSizeNumber { get; set; }
        public string ProductSizeAge { get; set; }
        public string ProductColor { get; set; }
        public string ProductStyle { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime SetOn { get; set; }
        public long SetBy { get; set; }
    
        public virtual ProductSection ProductSection { get; set; }
        public virtual ProductUnit ProductUnit { get; set; }
        public virtual PurchaseReceiveDetail PurchaseReceiveDetail { get; set; }
    }
}
