//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DAL.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLedger
    {
        public ProductLedger()
        {
            this.ProductLedgerDetails = new HashSet<ProductLedgerDetail>();
        }
    
        public long Id { get; set; }
        public string TransactionDate { get; set; }
        public long ProductId { get; set; }
        public int OpenQuantity { get; set; }
        public int ClosingQuantity { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime SetOn { get; set; }
        public long SetBy { get; set; }
    
        public virtual ICollection<ProductLedgerDetail> ProductLedgerDetails { get; set; }
    }
}
