//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DAL.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLedgerDetail
    {
        public long Id { get; set; }
        public long ProductLedgerId { get; set; }
        public Nullable<long> PurchaseReceiveDetailId { get; set; }
        public Nullable<long> PurchaseReturnDetailId { get; set; }
        public Nullable<long> SaleDetailId { get; set; }
        public Nullable<long> SaleReturnReceiveDetailId { get; set; }
        public int TransferQuantity { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime SetOn { get; set; }
        public long SetBy { get; set; }
    
        public virtual ProductLedger ProductLedger { get; set; }
    }
}
