//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DAL.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public long Id { get; set; }
        public long PurchaseReceiveDetailId { get; set; }
        public decimal PurchaseUnitPrice { get; set; }
        public decimal DiscountInPercentage { get; set; }
        public decimal ProductCost { get; set; }
        public decimal ProductSalePrice { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime SetOn { get; set; }
        public long SetBy { get; set; }
    
        public virtual PurchaseReceiveDetail PurchaseReceiveDetail { get; set; }
    }
}
