//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DAL.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseReceiveDetail
    {
        public PurchaseReceiveDetail()
        {
            this.ProductPrices = new HashSet<ProductPrice>();
            this.ProductStores = new HashSet<ProductStore>();
            this.PurchaseReturnDetails = new HashSet<PurchaseReturnDetail>();
        }
    
        public long Id { get; set; }
        public long PurchaseReceiveId { get; set; }
        public long PurchaseChallanDetailId { get; set; }
        public decimal ProductUnitPrice { get; set; }
        public int ProductQuantity { get; set; }
        public decimal TotalPrice { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime SetOn { get; set; }
        public long SetBy { get; set; }
    
        public virtual ICollection<ProductPrice> ProductPrices { get; set; }
        public virtual ICollection<ProductStore> ProductStores { get; set; }
        public virtual PurchaseChallanDetail PurchaseChallanDetail { get; set; }
        public virtual PurchaseReceive PurchaseReceive { get; set; }
        public virtual ICollection<PurchaseReturnDetail> PurchaseReturnDetails { get; set; }
    }
}
