//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DAL.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseChallan
    {
        public PurchaseChallan()
        {
            this.PurchaseChallanDetails = new HashSet<PurchaseChallanDetail>();
            this.PurchaseReceives = new HashSet<PurchaseReceive>();
        }
    
        public long Id { get; set; }
        public string ChallanNumber { get; set; }
        public System.DateTime ChallanDate { get; set; }
        public long SupplierId { get; set; }
        public string OrderBy { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime SetOn { get; set; }
        public long SetBy { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<PurchaseChallanDetail> PurchaseChallanDetails { get; set; }
        public virtual ICollection<PurchaseReceive> PurchaseReceives { get; set; }
    }
}
