//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DAL.Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLog
    {
        public long Id { get; set; }
        public long Username { get; set; }
        public string UserType { get; set; }
        public string LoginDeviceName { get; set; }
        public string LoginIP { get; set; }
        public System.DateTime LoginTime { get; set; }
        public System.DateTime LogoutTime { get; set; }
        public byte PasswordAttemptCount { get; set; }
    }
}
