//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DAL.Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.RoleWiseOperationPermissions = new HashSet<RoleWiseOperationPermission>();
            this.RoleWiseScreenPermissions = new HashSet<RoleWiseScreenPermission>();
            this.UserInformations = new HashSet<UserInformation>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime SetOn { get; set; }
        public long SetBy { get; set; }
    
        public virtual ICollection<RoleWiseOperationPermission> RoleWiseOperationPermissions { get; set; }
        public virtual ICollection<RoleWiseScreenPermission> RoleWiseScreenPermissions { get; set; }
        public virtual ICollection<UserInformation> UserInformations { get; set; }
    }
}
